# Generated by Django 4.1.2 on 2022-10-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.URLField(
                blank=True,
                default="https://www.personality-insights.com/wp-content/uploads/2017/12/default-profile-pic-e1513291410505.jpg",
                max_length=255,
                null=True,
            ),
        ),
    ]
