version: '3'
services:
  angular-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    container_name: angular-ui
    volumes:
       - ./ui:/usr/src/app/ui
       - /usr/src/app/ui/node_modules