version: "3.9"
services:
    drugstore-frontend:
        container_name: drugstore-frontend
        build:
            context: .
            dockerfile: ./ui/Dockerfile
        ports:
            - 4200:4200
        volumes:
            - /ui/node_modules
        command: ng serve --host 0.0.0.0 --port 4200
